#!/bin/bash

# This file is located in /home/momentum/.vnc/xstartup

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

bash /home/momentum/.vnc/vncstartup.sh # Our VNC Startup bash file